SELECT MEMBER_ID, MEMBER_NAME, GENDER, FORMAT(DATE_OF_BIRTH, 'YYYY-MM-DD') AS DATE_OF_BIRTH
from MEMBER_PROFILE
WHERE TLNO IS NOT NULL
AND GENDER = 'W'
AND MONTH(DATE_OF_BIRTH) = 03
ORDER BY MEMBER_ID ASC